apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akseu-662a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akseu-662a"
  template:
    metadata:
      labels:
        app: "akseu-662a"
    spec:
      containers:
        - name: "akseu-662a"
          image: "selfcr.azurecr.io/akseu"
          ports:
          - containerPort: 22